version: '3'

services:
    nutripod:
        environment:
            POSTGRES_DB: frd_proj
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
            NODE_ENV: production
            JWT_SECRET: "youaretheappleofmyeyes"
            PORT: 8080
        platform: linux/amd64
        depends_on:
            - postgres
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: "samor1014/nutripod:latest"
        ports:
            - "8080:8080"
    postgres:
        image: "postgres:13"
        environment:
            POSTGRES_DB: frd_proj
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data